In [2]:
import numpy as np

### Create Array using:
- **list** 
- **arange()** : Create an Array of evenly spaced values. 
    ```python
        np.arange(start,stop,step)
    ```  
- **linspace()** : Create an Array of evenly spaces values in a specific range given. Unlike arrange() which generates evenly space values witha defined steps, whereas linespace() divides range in eaqal portions. 
    ```python
        np.linspace(start,stop,num=10, endpoint = True)
    ```
- **zeros()** : Creates an Array of zeroes.
    ```python
        np.zeros(dimension)
    ```
- **ones()** : Creates an Array of ones.
    ```python
        np.ones(dimension)
- **empty()** : Create a new array of a given shape and data type, without initializing the entries.
    ```python
        np.empty(shape, dtype = float)
    ```
- **full()**: Creates a new array of given dimension and default value.
    ```python
        np.full(shape, fill_value, dtype = None)
    ```
- **eye()**: Creates a 2D array with ones on the diagonal and zeros elsewhere.
    ```python
        np.eye(3)
    ```

In [31]:
ls=[2,3,4]
arr1=np.array(ls)
print(f'Array using list: {arr1}')

arr2=np.arange(0,10,2)
print(f'Array using arrange(): {arr2}')

arr3=np.linspace(1,10,num=10,endpoint=True)
print(f'Array using linspace(): {arr3.astype(int)}')

arr4=np.zeros(5)
print(f'Array using zeros(): {arr4.astype(int)}')

arr5=np.ones(5)
print(f'Array using ones(): {arr5.astype(int)}')

arr6=np.empty(5,dtype=int)
print(f'Array using empty(): {arr6}')

arr7=np.full(5,12,dtype=int)
print(f'Array using full(): {arr7}')

print(f'Identity matrix using eye():\n{np.eye(3,dtype=int)}')

Array using list: [2 3 4]
Array using arrange(): [0 2 4 6 8]
Array using linspace(): [ 1  2  3  4  5  6  7  8  9 10]
Array using zeros(): [0 0 0 0 0]
Array using ones(): [1 1 1 1 1]
Array using empty(): [1 1 1 1 1]
Array using full(): [12 12 12 12 12]
Identity matrix using eye():
[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Reshape an array: 

In [28]:
# create 1D array
arr_reshape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

print("Array : " + str(arr_reshape))

# length of array
n = arr_reshape.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# converting it to 2-D from 1-D array
reshaped1 = arr_reshape.reshape((N, M))

# printing reshaped array
print(f"First Reshaped Array : with M: {M} and N: {N}")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(arr_reshape, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : with M: 4 and N: 4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


### Statistical function in numpy:
np.fun(arr)

### Dot Product
np.dot(arr1,arr2)